<a href="https://colab.research.google.com/github/jaiaakash5607/machine-learning/blob/main/Loan_Prediction_Problem_DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sms

In [2]:
data=pd.read_csv("/content/imbalanced_dataset.csv")
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001316,Male,Yes,0,Graduate,No,2958,2900.0,131.0,360.0,1.0,Semiurban,Y
1,LP001387,Female,Yes,0,Graduate,NaN,2929,2333.0,139.0,360.0,1.0,Semiurban,Y
2,LP001157,Female,No,0,Graduate,No,3086,0.0,120.0,360.0,1.0,Semiurban,Y
3,LP002297,Male,No,0,Graduate,No,2500,20000.0,103.0,360.0,1.0,Semiurban,Y
4,LP002141,Male,Yes,3+,Graduate,No,2666,2083.0,95.0,360.0,1.0,Rural,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,LP001543,Male,Yes,1,Graduate,No,9538,0.0,187.0,360.0,1.0,Urban,Y
468,LP002255,Male,No,3+,Graduate,No,9167,0.0,185.0,360.0,1.0,Rural,Y
469,LP002619,Male,Yes,0,Not Graduate,No,3814,1483.0,124.0,300.0,1.0,Semiurban,Y
470,LP001665,Male,Yes,1,Graduate,No,3125,2583.0,170.0,360.0,1.0,Semiurban,N
471,LP001529,Male,Yes,0,Graduate,Yes,2577,3750.0,152.0,360.0,1.0,Rural,Y

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472 entries, 0 to 471
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            472 non-null    object
 1   Gender             464 non-null    object
 2   Married            469 non-null    object
 3   Dependents         461 non-null    object
 4   Education          472 non-null    object
 5   Self_Employed      446 non-null    object
 6   ApplicantIncome    472 non-null    int64
 7   CoapplicantIncome  472 non-null    float64
 8   LoanAmount         458 non-null    float64
 9   Loan_Amount_Term   461 non-null    float64
 10  Credit_History     429 non-null    float64
 11  Property_Area      472 non-null    object
 12  Loan_Status        472 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 48.1+ KB

In [4]:
data.dropna(inplace=True)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 369 entries, 0 to 471
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            369 non-null    object
 1   Gender             369 non-null    object
 2   Married            369 non-null    object
 3   Dependents         369 non-null    object
 4   Education          369 non-null    object
 5   Self_Employed      369 non-null    object
 6   ApplicantIncome    369 non-null    int64
 7   CoapplicantIncome  369 non-null    float64
 8   LoanAmount         369 non-null    float64
 9   Loan_Amount_Term   369 non-null    float64
 10  Credit_History     369 non-null    float64
 11  Property_Area      369 non-null    object
 12  Loan_Status        369 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 40.4+ KB

In [6]:
data=data.drop("Loan_ID",axis=1)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 369 entries, 0 to 471
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             369 non-null    object
 1   Married            369 non-null    object
 2   Dependents         369 non-null    object
 3   Education          369 non-null    object
 4   Self_Employed      369 non-null    object
 5   ApplicantIncome    369 non-null    int64
 6   CoapplicantIncome  369 non-null    float64
 7   LoanAmount         369 non-null    float64
 8   Loan_Amount_Term   369 non-null    float64
 9   Credit_History     369 non-null    float64
 10  Property_Area      369 non-null    object
 11  Loan_Status        369 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 37.5+ KB

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le=LabelEncoder()
for i in data.columns:
  if data[i].dtype==object:
    data[i]=le.fit_transform(data[i])

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 369 entries, 0 to 471
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             369 non-null    int64
 1   Married            369 non-null    int64
 2   Dependents         369 non-null    int64
 3   Education          369 non-null    int64
 4   Self_Employed      369 non-null    int64
 5   ApplicantIncome    369 non-null    int64
 6   CoapplicantIncome  369 non-null    float64
 7   LoanAmount         369 non-null    float64
 8   Loan_Amount_Term   369 non-null    float64
 9   Credit_History     369 non-null    float64
 10  Property_Area      369 non-null    int64
 11  Loan_Status        369 non-null    int64
dtypes: float64(4), int64(8)
memory usage: 37.5 KB

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
y=data["Loan_Status"]
x=data.drop("Loan_Status",axis=1)

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [17]:
model.score(x_test,y_test)

0.8513513513513513

In [18]:
x_test.iloc[[0]]

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
415,1,0,2,0,0,4354,0.0,136.0,360.0,1.0,0

In [19]:
model.predict(x_test.iloc[[0]])

array([1])

In [20]:
y_test.iloc[0]

np.int64(1)